version: "3.8"

services:
    web:
        image: "nginx"
        container_name: "mynginx"
        ports:
            - "80:80"
        networks:
            my_network:
                ipv4_address: 172.29.0.2
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    php:
        #https://github.com/harrison9824003/docker/tree/master/php/fpm/swoole
        image: "php-fpm:swoole"
        container_name: "php-fpm"
        networks:
            my_network:
                ipv4_address: 172.29.0.3
        ports:
            - "9000:9000"
        links:
          - mysql
          - redis
        volumes:
            - .:/var/www/html
    mysql:
        image: "mysql:5.7"
        container_name: "mysql5.7"
        ports:
            - "3306:3306"
        networks:
            my_network:
                ipv4_address: 172.29.0.4
        volumes:
            - ./docker/mysql/log:/var/log/mysql
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/sqls/db.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
    redis:
        image: "redis"
        container_name: "redis"
        networks:
            my_network:
                ipv4_address: 172.29.0.5
        ports:
            - "6379:6379"
        privileged: true        
        volumes:
            - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
            - ./docker/redis/data:/data
        tty: true
networks:
    my_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16
                  gateway: 172.29.0.1